services:
  zenova-app:
    build: .
    container_name: zenova_container
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./data/database.sqlite
    volumes:
      - C:/zenova-data:/app/src/server/data
    develop:
      watch:
          - path: ./src
            action: rebuild
    env_file:
      - .env
